Repository octokit/octokit.graphql.net, pull requests merged in 2018-07, with the labels that each got.

#124 Fix-up code samples
  docs/compiling-queries.md
  docs/paging.md
  docs/quickstart.md
  readme.md
Labels: ready-for-review

#117 Adding developer documents
  docs/contributing.md
  docs/readme.md
Labels: documentation, ready-for-review

#127 GraphQL Checks API requires preview header
  Octokit.GraphQL.Core/Connection.cs
Labels: bug, ready-for-review

#126 Adding functionality to specify a PageSize to AllPages
  Octokit.GraphQL.Core.UnitTests/PagingTests.cs
  Octokit.GraphQL.Core/Core/Builders/AllPagesExpression.cs
  Octokit.GraphQL.Core/Core/Builders/QueryBuilder.cs
  Octokit.GraphQL.Core/PagingConnectionExtensions.cs
Labels: enhancement, ready-for-review

#102 Fragment Query Support
  Octokit.GraphQL.Core.UnitTests/QueryBuilderTests.cs
  Octokit.GraphQL.Core/Core/Builders/QueryBuilder.cs
  Octokit.GraphQL.Core/Core/Builders/Rewritten.cs
  Octokit.GraphQL.Core/Core/Serializers/QuerySerializer.cs
  Octokit.GraphQL.Core/Core/Syntax/FragmentDefinition.cs
  Octokit.GraphQL.Core/Core/Syntax/FragmentSpread.cs
  Octokit.GraphQL.Core/Core/Syntax/OperationDefinition.cs
  Octokit.GraphQL.Core/Core/Syntax/SyntaxTree.cs
  Octokit.GraphQL.Core/Fragment.cs
  Octokit.GraphQL.Core/IFragment.cs
  Octokit.GraphQL.Core/QueryableListExtensions.cs
  Octokit.GraphQL.Core/QueryableValueExtensions.cs
  Octokit.GraphQL.IntegrationTests/Queries/RepositoryTests.cs
  Octokit.GraphQL.UnitTests/ExpressionRewiterTests.cs
  docs/fragments.md
  docs/readme.md
Labels: ready-for-review

#137 Fixing words
  docs/contributing.md
Labels: ready-for-review
